"""
Extended converter.py — dependency-aware code transformation.
Existing single-file convert_code() API remains intact.
New convert_code_with_context() adds cross-file dependency context to Gemini.
"""
import json
from typing import Dict, Any, Optional
from app.llm_provider import llm_provider


class CodeConverter:

    def convert_code(self, spec_json_str: str, business_rules_json_str: str, target_language: str = "Python") -> str:
        """
        Module 2: Spec-grounded target code generation (backward compatible).
        """
        try:
            spec = json.loads(spec_json_str)
            rules = json.loads(business_rules_json_str)
        except Exception:
            spec = {"summary": "Healthcare logic routine"}
            rules = ["Preserve all parameter validation and output structures"]

        prompt = self._build_single_file_prompt(spec, rules, target_language)
        generated = llm_provider.generate_completion(
            prompt,
            system_instruction=f"Generate production-grade, highly readable {target_language} code preserving exact business logic."
        )
        return self._clean_code(generated, target_language)

    def convert_code_with_context(
        self,
        spec_json_str: str,
        business_rules_json_str: str,
        target_language: str,
        source_file: str,
        dependency_context: str,
        interface_contract: Optional[Dict] = None,
        converted_deps_summary: str = "",
        source_language: str = "MUMPS",
        traceability_id: int = None,
    ) -> str:
        """
        Dependency-aware code conversion with full project context window.
        This is the primary path for multi-file workspace conversion.
        """
        try:
            spec = json.loads(spec_json_str)
            rules = json.loads(business_rules_json_str)
        except Exception:
            spec = {"summary": "Healthcare logic routine"}
            rules = ["Preserve all parameter validation and output structures"]

        # Build traceability header
        trace_header = ""
        if traceability_id:
            trace_header = f"# Modernized from: {source_file}\n# ErrorX404 conversion_id: {traceability_id}\n# DO NOT EDIT — generated by ErrorX404 AI Pipeline\n\n"

        contract_str = ""
        if interface_contract:
            contract_str = f"""
=== INTERFACE CONTRACT FOR THIS MODULE ===
You MUST implement all exports listed in this contract with the exact signatures shown.
{json.dumps(interface_contract, indent=2)}
"""

        prompt = f"""
You are converting one component of a larger legacy application from {source_language} to {target_language}.

DO NOT treat the current file as an isolated program.
DO NOT invent dependencies that don't exist in the dependency context.
DO NOT remove dependencies without providing an equivalent replacement.
If a dependency cannot be safely translated, mark it as: # REVIEW_REQUIRED: <reason>

=== SOURCE FILE ===
{source_file}

{dependency_context}

{contract_str}

=== BUSINESS SPECIFICATION ===
{json.dumps(spec, indent=2)}

=== EXPLICIT BUSINESS RULES TO PRESERVE (HIGHEST PRIORITY) ===
{json.dumps(rules, indent=2)}

=== REQUIREMENTS ===
1. Implement clean object-oriented or modular {target_language} code.
2. Every business rule MUST have a docstring/comment reference (e.g., # RULE-1: ...).
3. ALL cross-file dependencies shown in the dependency map MUST be preserved as imports or equivalent.
4. If this module depends on another converted module, generate: from <module_name> import <symbol>
5. If this module's interface contract lists exports, implement ALL of them with matching signatures.
6. Include error handling and clean data structures.
7. Output ONLY executable, syntactically valid {target_language} code.
8. Begin the file with the traceability header comment if applicable.
9. For MUMPS globals (e.g. ^DPT, ^PSRX), generate a repository/DAO abstraction or dict-based storage.
10. Preserve all function parameter names and return value semantics.

Preserve:
- Business rules
- Function behavior and signatures
- Inputs/outputs
- Cross-file dependencies  
- Database dependencies (MUMPS globals → Python dict/ORM)
- API dependencies
- Shared data relationships
- Error behavior
- External calls
"""

        generated = llm_provider.generate_completion(
            prompt,
            system_instruction=(
                f"You are converting one module of a larger legacy {source_language} application to {target_language}. "
                "Preserve ALL cross-file dependencies. Generate production-grade code. "
                "Never silently drop a dependency — if unsure, mark it REVIEW_REQUIRED."
            )
        )
        cleaned = self._clean_code(generated, target_language)

        # Prepend traceability header if not already present
        if trace_header and "# Modernized from:" not in cleaned:
            cleaned = trace_header + cleaned

        return cleaned

    def _build_single_file_prompt(self, spec: dict, rules: list, target_language: str) -> str:
        return f"""
You are an expert software engineer converting legacy spec specifications into idiomatic, robust {target_language} code.

BUSINESS SPECIFICATION:
{json.dumps(spec, indent=2)}

EXPLICIT BUSINESS RULES TO PRESERVE (MAIN FOCUS):
{json.dumps(rules, indent=2)}

REQUIREMENTS:
1. Implement clean object-oriented or modular {target_language} code.
2. Every business rule MUST have a docstring reference (e.g., # RULE-1: ...).
3. Include error handling and clean data structures.
4. Output ONLY executable, syntactically valid {target_language} code, with no markdown code blocks surrounding if possible, or clean standard code blocks.
"""

    def _clean_code(self, generated: str, target_language: str) -> str:
        cleaned = generated
        lang_lower = target_language.lower()
        if f"```{lang_lower}" in cleaned:
            cleaned = cleaned.split(f"```{lang_lower}")[1].split("```")[0]
        elif "```python" in cleaned:
            cleaned = cleaned.split("```python")[1].split("```")[0]
        elif "```r" in cleaned:
            cleaned = cleaned.split("```r")[1].split("```")[0]
        elif "```" in cleaned:
            parts = cleaned.split("```")
            # Take the longest code block
            code_blocks = [parts[i] for i in range(1, len(parts), 2)]
            if code_blocks:
                cleaned = max(code_blocks, key=len)
        return cleaned.strip()
